# Generated by Django 5.1.3 on 2024-12-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_reservada', models.PositiveIntegerField()),
                ('date_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado_reserva', models.CharField(default='Pendiente', max_length=50)),
                ('ci', models.ForeignKey(db_column='ci', on_delete=django.db.models.deletion.CASCADE, to='registro.usuario')),
                ('id_pro', models.ForeignKey(db_column='id_pro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
