# Generated by Django 5.1.3 on 2025-01-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_talla_remove_producto_talla_producto_tallas'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tallas',
            field=models.ManyToManyField(blank=True, to='catalogo.talla'),
        ),
    ]
