# Generated by Django 5.1.3 on 2025-01-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_talla_remove_producto_talla_producto_tallas'),
        ('citas', '0002_reserva_tallas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tallas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='talla',
            field=models.ForeignKey(db_column='id_talla', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.talla'),
        ),
    ]
