# Generated by Django 4.2.9 on 2025-05-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255)),
                ('subtema', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_ci', null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.usuario')),
            ],
            options={
                'db_table': 'contactos_comentario',
            },
        ),
    ]
