# Generated by Django 4.2.9 on 2024-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('tel', models.CharField(max_length=10, unique=True)),
                ('contrasenia', models.CharField(max_length=100)),
                ('birth', models.DateField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
