"""
Django settings for Tesis project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import json
import tempfile

load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar el entorno
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')  # 'production' para Render, 'development' para local
IS_PRODUCTION = ENVIRONMENT == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-g20qnv71m8=qjupy9zj11s53+y5%&*h3bx9*$gdn*yx3j8#p9m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# Configuración de hosts permitidos según el entorno
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['sistemacrixball.onrender.com']
else:
    # Para desarrollo local con ngrok
    ALLOWED_HOSTS = [
        'localhost', 
        '127.0.0.1',
        '*.ngrok-free.app',  # Permite cualquier subdominio de ngrok
        '*.ngrok.io',        # Para URLs de ngrok anteriores
    ]
    
    # Si tienes una URL específica de ngrok, agrégala aquí
    NGROK_URL = os.getenv('NGROK_URL')  # ej: 'abc123.ngrok-free.app'
    if NGROK_URL:
        ALLOWED_HOSTS.append(NGROK_URL)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'autenticacion',
    'acerca',
    'catalogo.apps.CatalogoConfig', 
    'citas',
    'contactos',
    'Tesis',
    'registro',
    'chatbot',
    'cloudinary',
    'cloudinary_storage',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tesis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tesis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if IS_PRODUCTION:
    # Configuración para producción (Render)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
else:
    # Configuración para desarrollo local con PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('LOCAL_DB_NAME', 'tesis_local'),
            'USER': os.getenv('LOCAL_DB_USER', 'postgres'),
            'PASSWORD': os.getenv('LOCAL_DB_PASSWORD', ''),
            'HOST': os.getenv('LOCAL_DB_HOST', 'localhost'),
            'PORT': os.getenv('LOCAL_DB_PORT', '5432'),
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de Cloudinary (solo en producción)
if IS_PRODUCTION:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'Autenticacion' 

# Configuración de sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 60 * 60 * 24  # 24 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# MEDIA URL
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de CSRF para ngrok
if not IS_PRODUCTION:
    NGROK_URL = os.getenv('NGROK_URL')
    if NGROK_URL:
        CSRF_TRUSTED_ORIGINS = [f'https://{NGROK_URL}', f'http://{NGROK_URL}']

# Chatbot - Configuración de Google Dialogflow
credenciales_json = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

if credenciales_json:
    try:
        credenciales_dict = json.loads(credenciales_json)
        temp_cred_file = tempfile.NamedTemporaryFile(delete=False, suffix=".json")
        temp_cred_file.write(json.dumps(credenciales_dict).encode())
        temp_cred_file.close()
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = temp_cred_file.name
        print(f"✅ Credenciales de Dialogflow guardadas en: {temp_cred_file.name}")
    except json.JSONDecodeError:
        print("❌ ERROR: La variable GOOGLE_APPLICATION_CREDENTIALS no contiene un JSON válido.")
else:
    print("❌ ERROR: No se encontró la variable GOOGLE_APPLICATION_CREDENTIALS.")

# Logging para desarrollo (opcional - para ver consultas SQL)
if not IS_PRODUCTION:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.db.backends': {
                'level': 'DEBUG',
                'handlers': ['console'],
            }
        }
    }

SALEOR_API_URL = "http://localhost:8001/graphql/"
SALEOR_USER_EMAIL = "paguayximena4@gmail.com" 
SALEOR_USER_PASSWORD = "Erika.2020"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}