# Generated by Django 4.2.9 on 2025-05-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('usuario', 'usuario'), ('bot', 'bot')], max_length=10)),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.usuario')),
            ],
            options={
                'db_table': 'historial_chat',
                'ordering': ['timestamp'],
            },
        ),
    ]
