# Generated by Django 5.1.3 on 2024-12-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id_rama', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_rama', models.CharField(max_length=255)),
                ('id_cat', models.ForeignKey(db_column='id_cat', on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
            ],
            options={
                'db_table': 'rama',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=255)),
                ('detalle_pro', models.TextField()),
                ('precio_pro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_pro', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('id_rama', models.ForeignKey(db_column='id_rama', on_delete=django.db.models.deletion.CASCADE, to='catalogo.rama')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
