# Generated by Django 5.1.3 on 2025-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
