# Generated by Django 5.1.3 on 2025-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
