# Generated by Django 5.1.3 on 2025-01-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_producto_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'talla',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(related_name='productos', to='catalogo.talla'),
        ),
    ]
