# Generated by Django 5.1.3 on 2025-01-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_productotalla'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productotalla',
            table='producto_talla',
        ),
    ]
