# Generated by Django 5.1.3 on 2025-01-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_productotalla_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_pro',
        ),
    ]
