# Generated by Django 5.1.3 on 2025-01-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_remove_producto_precio_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_disponible',
        ),
    ]
