# Generated by Django 5.1.3 on 2025-01-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_producto_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(blank=True, related_name='productos', to='catalogo.talla'),
        ),
    ]
