# Generated by Django 5.1.3 on 2025-01-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_producto_tallas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tallas',
        ),
    ]
