# Generated by Django 4.2.9 on 2025-03-31 00:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_pro',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
