# Generated by Django 4.2.9 on 2025-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_producto_imagen_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='saleor_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
