# Generated by Django 4.2.9 on 2026-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0013_producto_saleor_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ci_usuario", models.CharField(max_length=10)),
                ("numero_orden", models.CharField(max_length=50)),
                ("metodo_pago", models.CharField(max_length=30)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(default="USD", max_length=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "comprobante",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
